---
title: "From physical oceanography to fisheries: Supporting data e-fish-iency at the Southeast Fisheries Science Center"
subtitle: Preparatory narration
format:
  html:
    from: "markdown+emoji"
---

It occurred to me that most of you were probably born while I was sitting where you are as an undergraduate at Florida Tech. That makes me feel unpleasantly old, but such is life! Had anyone told me 20 years ago as I sat there as a physical oceanography major with a meteorology minor that I would one day work for NOAA Fisheries, I would have laughed in their face and told them they were out of their minds! NOAA Fisheries is the part of NOAA responsible for the stewardship of the nation’s ocean resources and their habitats, but I never liked biology, neither in high school nor at Florida Tech. In fact, I nearly failed it there. My excuse is that for the biology lab at the time we had to draw what we saw in lab notebooks and then later, on exams, identify specimens from our drawings alone. The problem is, I cannot draw to save my life. For example, every fish I drew looked something like this... :next_track_button:

...which turns out to be completely rubbish for learning anything! It's like trying identify a person from a stick figure drawing. Nowadays I'm sure you all can just take pictures with your phones, which hopefully would have helped me out, but instead I concluded I was too lousy of an artist to be a biologist of any kind and wanted nothing to do with biology.

But before I go any further, the obligatory float plan :next_track_button: for the evening: I've been asked to talk about my career as a civil servant with NOAA, what that looks like and how I got here. I've decided to do that from the perspective of an abbreviated career talk. I myself have always enjoyed learning about colleagues' career paths because, even to this day, I always find myself surprised and, frankly, inspired, by their stories. It's helpful to be reminded that scientists' careers are rarely linear and predictable. And finally, in case I successfully inspire one or more of you to consider a career in government, I'll end with some suggestions for how to make that dream become a reality. 

I'd like to start with a quote from my Master's advisor that really resonated with me and that I remember to this day. A few months into my first year at the University of Delaware, my lab mate and I were figuring out how to balance our course work and thesis research while also going to sea for a week at a time every month to support another unrelated project my advisor had funded. Matt Oliver, our advisor, sat us down for a pep talk, as he did from time to time, and said to us :next_track_button::

> Courses don’t get people jobs. And neither do degrees or theses or dissertations, for that matter. *Skills* get people jobs. The best thing you can do as a student is to start searching for jobs now, even though you still have time to go. Look for jobs that excite you, things that you’d like to do, and then see what skills they’re looking for. If there are things you don’t already know how to do, use the next year or so to learn it. Being in school is the best time to develop your skill toolbox! You never know what skill will land you your first job.

These words of wisdom have really rung true in my career, so listen for them resonating throughout this evening. They also sparked a paradigm shift in how I approached the rest of my education. I had been thinking about working for NOAA since my time as an undergraduate, but I didn't know what that would look like or how to make it happen. I assumed that having the right degrees with the right classes would do the trick, but as it turns out Matt was right: skill building was key.

I have to give credit where credit is due: Matt Oliver was a fantastic advisor and mentor who was always trying to set us up for success both during and after our time in his lab. In addition to the cruise experience, another opportunity I had as a Master's student was learning to operate :next_track_button: Slocum gliders, which are low-powered buoyancy-driven autonomous underwater vehicles that can measure a host of physical, chemical, and biological properties in the ocean. Matt sent us to glider school to learn how to prep, deploy, pilot, and recover these instruments and arranged to have us test our skills in the Delaware Bay and eventually offshore. It was a lot of fun, but had nothing to do with my research project. As I was finishing up my Master's :next_track_button:, an oil rig called the Deepwater Horizon exploded in the northern Gulf of America and :next_track_button: spilled millions of gallons of oil into the water over thirty-something days before it was finally contained. It was an environmentally devastating event to watch play out, but it was also paradoxically inspiring as a student to see the entire oceanographic community across the country spring into action to help out. This included in glider community, and so we prepped our glider and went on standby in case we were asked to bring it down to Louisiana.

Fast forward a few years and I landed a job as a research associate in the Ocean Observation Laboratory at the University of Massachusetts Dartmouth School for Marine Science and Technology. :next_track_button: They needed someone to, among other things, manage their glider program. This is a video of a glider in their large acoustic test tank where I'd ballast and test it before deploying. I was the only applicant who had that training and experience, I later found out. My Master's degree did not get me that job -- in fact, it was advertised as "Bachelor's required, Master's preferred" -- those glider piloting skills got me the job.

I did that for a couple years before deciding to back to school for my Ph.D. at the University of Miami with Dr. Tamay Ozgokmen. He's an interesting character himself: he spent the first decade of his career as an ocean modeler and made fun of sea-going oceanographers who got sea sick collecting small amounts of data. He was convinced that he could learn more about the ocean from the comfort of his office using circulation models. Then the Deepwater Horizon oil spill happened and he quickly learned that even the best circulation models failed to predict where the oil would go. :next_track_button: So he then spent the next decade of his career conducting large scale field campaigns in the Gulf to better understand the material transport problem. Here's one of the outreach videos that we used to explain our work to the general public.

So that's where I came in. Tamay needed someone to dig into those data to help pioneer the "next generation of ocean circulation models." So, he brought me on as a Ph.D. student because of my experience gathering and analyzing oceanographic data and gave me considerable freedom to define my own research problem, which was a rather unique, though also daunting, experience. Meanwhile, he had become intrigued by machine learning and how it might become the future of oceanographic modeling, like it has in so many other fields. :next_track_button: I decided to make my dissertation research about testing machine learning with the drifter data from the large scale field experiments in that video. The biggest barrier to marine science adaptation of machine learning has been and largely continues to be the availability of - or, more accurately, the lack thereof - data. As you know, machine learning models are data hungry. That's the whole premise behind them. So, our thinking was, if machine learning is going to work anywhere in the ocean circulation problem, hopefully it'll work in this rare case of having over 5 million data points from a single type of instrument (drifters). I don't have time tonight to go into detail about that work, but I came out of that program as an observational physical oceanographer with machine learning experience, a unique combination of skills that, at the time, turned out to be quite marketable, because I finally landed my first NOAA job offer as I was finishing up my Ph.D. I later learned that my first supervisor liked my machine learning experience because they needed that expertise in house, but also liked my past observational oceanography experience because it showed that I understood not just the data themselves, but how the data are collected and all the complexities and complications that go with that.

:next_track_button: So now, here am I, one who avoided all things biology in school, working at, of all places, at the Southeast Fisheries Science Center I work with amazingly passionate and dedicated scientists, such as my colleague who retired this month after a remarkable 41 years of service during which he contributed to nearly every survey and shipboard research project based out of his lab and logged nearly 120 sea days this year alone before retiring. We are all distributed across a number of labs and facilities from Texas though the Caribbean and up to North Carolina, where I'm located, and we carry out an inspiring and motivating mission of *providing the scientific advice and data needed to effectively manage the living resources of the Southeast Region and Atlantic high seas.* We do this by partnering with fisheries management councils, fisheries commissions, and federal, state, and local agencies to, among many other things, carry out annual stock assessments for key species throughout the region. These assessments are always rooted in independent, objective science and contain such information as population estimates (counts), spatial distributions, age distributions, and the overall health of the particular species. This kind of information is then used to inform consequential policy decisions such as where can people fish and when, how much of each species can be kept, and things like that.

I'm a data scientist now, which means I'm not technically doing oceanography, but I'm solving technical problems related to the ocean, which I enjoy. My job is to collaborate with scientists all across the Center to understand the ways in which we are collecting data, processing it, and converting into useful information, and then find ways to streamline, modernize, and automate our workflows where possible. I personally have come to really enjoy automating things, even outside of work. It's just...oddly satisfying!  So my team and I are identifying parts of our mission that could be well-suited for machine learning and automation so that our limited staff and funding can be allocated to tasks that machines are not good at. Some examples of projects we have going on that I'm overseeing :next_track_button::

**Fish identification:** :next_track_button: One way we improve stock assessments is by observing fish habitats and water quality to derive estimates of abundance, size, and community composition for key species in the region. :next_track_button: We do this by deploying cameras underwater and recording fish in their natural habitat. We use a system of 4-5 outward-looking cameras to get a 360&deg; view, mount them into a protective cage along with other oceanographic instruments for measuring oceanographic data, and lower it off the ship to record 20–30-minute videos at roughly 2000 randomly selected locations throughout the region each year. As you might expect, this results in many terabytes of video data that need to be processed. The traditional method is for expert scientists to sit in dark rooms and watch the videos all day every day to find, identify, and count fish species on each frame in each video. It's a very time-consuming process, and it currently takes us more than a year to process one year's worth of video. So obviously that's not sustainable; we can't keep up! So, this has become one candidate for machine learning since the rise of high performing computer vision models. We're currently deploying models that identify key species of fish in the videos and track them from frame to frame so that we can quickly get estimates of how many of each species are present, which we anticipate will shave off many months of processing time. But this is not without its challenges: visibility underwater changes from site to site, day to day, which can make some of the videos very difficult if not impossible to process. We also have a highly unbalanced data set, with some species being seen very often and others very rarely. So there is always room for more data and ongoing research and development as the machine learning field rapidly advances.

**Fish aging:** :next_track_button: Species counts is only one metric for habitat monitoring. :next_track_button: We also need to know the age distribution of those species because this allows us to estimate fish mortality rate from year to year, to determine reproductive maturity of the stock, and to monitor changes in population over time. If, for example, the vast majority of individuals in a given year are juvenile, it would be in our best management interest to limit fishing of that species so that those juveniles can grow and reproduce, lest we fish them out of existence. On the other hand, if all of the individuals are older or...shall we say, elderly fish...we know something is wrong that is either preventing reproduction or affecting the survival rate of young. So each year scientists collect samples of key species to be aged at a lab. Some species, like Atlantic and Gulf menhaden, are aged by looking at a scale under a microscope, while :next_track_bottom: other species are aged using an otolith, a small ear bone that grows as the fish grows. :next_track_button: In both cases, scientists look for and count rings or similar signals, much like counting tree rings. :next_track_button: Again, this has traditionally been done by humans, but we have trained computer vision and statistical models for a few initial species that can do much of this for us in a fraction of the time.

:next_track_button: There are numerous other examples of exciting and promising work like this all throughout the agency. I really see this kind of innovation, along with cloud adaptation and the rise of uncrewed systems for data collection across all of NOAA's mission, as being areas of substantial growth in the years to come. But of course the commitment to other research and operational science will always be there too. NOAA's mission spans from the surface of the sun to the sea floor, and we do everything from research and science to policy and governance to education and outreach, all of which require a highly diverse workforce of domain scientists, communicators, lawyers, policy makers, law enforcement, budget folks, facilities support, IT, just to name a few...there is literally something for everyone.

Ok, so what if you're interested in working for NOAA or another federal agency; how does one make that happen? I'll offer a few ideas to conclude. First, I'll return to my former advisor's advice: start looking for government jobs and take note of what skills they require. For federal positions, specialized skills and experience are absolutely essential to qualifying for any job. Much more so than the private sector. So, start looking now, no matter what year you're in. It's never too early to figure out what skills to develop before you need them. The vast majority of federal jobs are posted on USAJOBS and every job will have a Qualifications section that describes the specialized experience you need to qualify. That could be a whole different seminar so I won't go into details today.

Don't rule out government contractor jobs either, especially for non-citizens. Contractors and affiliate staff make up about half of our workforce at NOAA and are essential to carrying out our mission. We literally could not do it without them. These folks work for either private companies that usually exist solely for government contracts or at some universities throughout the country with whom we have cooperative agreements. These are called "cooperative institutes", there are about 15 of them I believe, each one specializing in and supporting a different part of NOAA's mission. There are advantages and disadvantages to both federal and contractor careers, but again, that could be a different seminar. Contractor positions will be advertised on their company or university sites, so you'll often find them on job platforms like LinkedIn or Indeed.

I also invite you to check out the NOAA Corps, especially if things flying hurricane hunters and driving ships excites you. I honestly did not know about the NOAA Corps until later in my academic preparation, but that is such a unique opportunity, though certainly not for everyone.

NOAA also offers many opportunities for student internships for both undergraduate and graduate students. Just Google "NOAA internships" and you'll find a number of pages. Each line office generally handles these separately, so find the parts of NOAA that appeal to you and check them out. Some of these opportunities include Sea Grant internships, the William M. Lapenta Student Internship Program, and others. And I'll also point out, something I did not know until much later, that the federal government has different hiring paths, meaning different ways you can qualify for jobs. One of these is a "recent graduates" path, which allows us to post entry level jobs designed specifically for recent graduates, which usually means within 5 years of graduation. So, you can look for these specifically on USAJOBS; NOAA definitely uses them when we can, and many other agencies do as well. Feel free to reach out to NOAA staff; we're busy and get lots of emails every day, but the vast majority of folks will happily respond to student inquiries. You just need to be patient sometimes. :next_track_button: Here is my email address, so feel free to reach out to me any time if you have questions. I'll do my best to help.

I've enjoyed being with you all tonight, it's great to be back at Florida Tech, even if virtually! It's very hard to believe how many years have gone by since I last sat where you are, so enjoy your time and experience there. And no matter where you are in your academic preparation, or where you want to end up as a job or career, if you remember one thing from tonight, remember that skills get people jobs. Do well in your classes, yes, because you need to gain subject matter expertise, but use your time as a student wisely to learn as much as you can outside of the classroom. The fact that you're here this evening tells me you're on that right track already. It's an extracurricular activity that you're doing on your time, a professional organization that you're plugging into. You're inviting, listening to, and learning from speakers. You're curiously asking questions and proactively wanting to know about career options. This is all very good stuff, so I applaud you for that. Keep up the good work, and GO PANTHERS!
